### ISSUE TITLE
Hi costs due RAILWAY_TCP_PROXY_DOMAIN

### ISSUE THREAD

**Issue by Huararanga** [rpuls/vendure-boilerplate#1]
Hi rpuls,
thank you very much for your posts It help me a lot with vendure.

After deploying everything the project eat pretty much money without real use. I found this is because db and backend was talking through public proxy (PGHOST="${{RAILWAY_TCP_PROXY_DOMAIN}}")

<img width="578" alt="image" src="https://github.com/user-attachments/assets/e73bb739-8710-4ef1-857a-3f41ea775216">

I resolved this issue by adding
PGPRIVATEPORT="5432"
to db env variables
and
DB_HOST="${{Postgres.PGPRIVATEHOST}}"
DB_PORT="${{Postgres.PGPRIVATEPORT}}"
to backend env variables

**Comment by rpuls** [comment]
@Huararanga Great discovery, thank you very much for sharing! I did notice excessive egress, but never got to the bottom of the issue. This is absolutely great! 🙏 I will test it out ASAP, and add it to the template if I see same result as you

**Comment by rpuls** [comment]
@Huararanga Thanks to your finding, these 3 environment variables have been added to the deploy template on railway.

**Comment by Huararanga** [comment]
Thank you too for the starter. I am looking forward for your Vendure email setup video. L
